name: 'App Center publish release'
description: 'GitHub Action to use publish a build via the "appcenter distribute release" CLI command. Testers will not be notified via email.'
author: 'Mitch Ware'
inputs: 
  app_name:
    description: 'App name, as defined by the AppCenter API (<ownerName>/<appName> format)'
    required: true 
  group_name:
    description: 'Group name, as defined by the AppCenter API. Can be a comma-separated list of multiple groups'
    required: true 
  file_path:
    description: 'Path to the app binary file to upload'
    required: true 
  token:
    description: 'API token - you can get one from appcenter.ms/settings'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    APP_NAME: ${{ inputs.app_name }}
    GROUP_NAME: ${{ inputs.group_name }}
    FILE_PATH: ${{ inputs.file_path }}
    API_TOKEN: ${{ inputs.token }}

