name: Example workflow for App Center action
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: Action test
        with:
          app_name: ${{ secrets.app_name }}
          group_id: ${{ secrets.group }}
          file_path: ${{ secrets.app_name }}
          token: ${{ secrets.APP_CENTER_API_TOKEN }}
